In [1]:
import numpy as np

In [61]:
# Crear un vector de ceros de tamaño 10
vector_ceros = np.zeros(10)
vector_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
vector_ceros = np.zeros(10)
vector_ceros[5] = 1
vector_ceros

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [8]:
# Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.
vector_50 = np.arange(50)
vector_50[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [62]:
# Crear una matriz de 3 x 3 con valores del cero al 8
matriz = np.arange(0,9,1).reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
# Encontrar los indices que no sean cero en un arreglo
arreglo = [1,2,0,0,4,0]
np_arreglo = np.array(arreglo)
np.where(np_arreglo != 0)

(array([0, 1, 4], dtype=int64),)

In [64]:
# Crear una matriz de identidad 3 x 3
matriz = np.eye(3)
matriz

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
# Crear una matriz 3 x 3 x 3 con valores randomicos
arreglo_random = np.random.rand(3,3,3)
arreglo_random

array([[[0.29455133, 0.96687478, 0.94393753],
        [0.02351031, 0.8022842 , 0.76413454],
        [0.41386859, 0.856485  , 0.48519025]],

       [[0.83095392, 0.05954419, 0.12013129],
        [0.46465355, 0.76352431, 0.84276251],
        [0.07242014, 0.85520792, 0.75027634]],

       [[0.21103644, 0.295141  , 0.26363892],
        [0.34619601, 0.5986419 , 0.90922172],
        [0.60622802, 0.12948262, 0.05667688]]])

In [47]:
# Crear una matriz 10 x 10 y encontrar el mayor y el menor
matriz = np.arange(50, 100, 0.5).reshape(10,10)
print(matriz)
print(np.min(matriz)) 
print(np.max(matriz))

[[50.  50.5 51.  51.5 52.  52.5 53.  53.5 54.  54.5]
 [55.  55.5 56.  56.5 57.  57.5 58.  58.5 59.  59.5]
 [60.  60.5 61.  61.5 62.  62.5 63.  63.5 64.  64.5]
 [65.  65.5 66.  66.5 67.  67.5 68.  68.5 69.  69.5]
 [70.  70.5 71.  71.5 72.  72.5 73.  73.5 74.  74.5]
 [75.  75.5 76.  76.5 77.  77.5 78.  78.5 79.  79.5]
 [80.  80.5 81.  81.5 82.  82.5 83.  83.5 84.  84.5]
 [85.  85.5 86.  86.5 87.  87.5 88.  88.5 89.  89.5]
 [90.  90.5 91.  91.5 92.  92.5 93.  93.5 94.  94.5]
 [95.  95.5 96.  96.5 97.  97.5 98.  98.5 99.  99.5]]
50.0
99.5


In [ ]:
# Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)


In [ ]:
# ¿Como crear una serie de una lista, diccionario o arreglo?
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

import pandas as pd
serie_a = pd.Series(mylist)
serie_b = pd.Series(myarr)
serie_c = pd.Series(mydict)


In [67]:
# ¿Como convertir el indice de una serie en una columna de un DataFrame?
import numpy as np
import pandas as pd

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 

# Transformar la serie en dataframe y hacer una columna indice

df1 = pd.DataFrame(ser)
df1.index = ['A']


In [ ]:
# ¿Como combinar varias series para hacer un DataFrame?
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

import pandas as pd
df1 = pd.DataFrame(ser1)
ser1 = df1[0]
ser2 = df1[1]


In [ ]:
# ¿Como obtener los items que esten en una serie A y no en una serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])