In [3]:
#pip install numpy
import numpy as np


In [5]:
print(type(array([1,2,3])))
print(type(array((1,2,3))))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

numpy.ndarray

In [6]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
np.arange(4,20) #[4,20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [11]:
arreglo_pares = np.arange(0,20,2)

In [10]:
np.arange(-12,12,0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5,   1. ,
         1.5,   2. ,   2.5,   3. ,   3.5,   4. ,   4.5,   5. ,   5.5,
         6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5,  10. ,
        10.5,  11. ,  11.5])

In [12]:
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape) #obtener el numero de dimensiones

10
10
(2, 3, 4)


In [13]:
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [15]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [17]:
combinaciones = np.arange(24)

In [18]:
combinaciones.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
combinaciones.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
combinaciones.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [21]:
combinaciones.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [22]:
combinaciones.reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [23]:
combinaciones.reshape(4,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [24]:
np.arange(24).reshape(6,4).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [25]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [26]:
# suma
a+b

array([15, 15, 15])

In [27]:
# resta
a-b

array([5, 5, 5])

In [28]:
# multiplicacion
a*b

array([50, 50, 50])

In [29]:
# division
a/b

array([2., 2., 2.])

In [52]:
c = np.arange(50,100,0.8)
d = np.arange(-20,11.5,0.5)

In [53]:
c + d

array([ 30. ,  31.3,  32.6,  33.9,  35.2,  36.5,  37.8,  39.1,  40.4,
        41.7,  43. ,  44.3,  45.6,  46.9,  48.2,  49.5,  50.8,  52.1,
        53.4,  54.7,  56. ,  57.3,  58.6,  59.9,  61.2,  62.5,  63.8,
        65.1,  66.4,  67.7,  69. ,  70.3,  71.6,  72.9,  74.2,  75.5,
        76.8,  78.1,  79.4,  80.7,  82. ,  83.3,  84.6,  85.9,  87.2,
        88.5,  89.8,  91.1,  92.4,  93.7,  95. ,  96.3,  97.6,  98.9,
       100.2, 101.5, 102.8, 104.1, 105.4, 106.7, 108. , 109.3, 110.6])

In [56]:
# Mod
a % b

array([0, 0, 0], dtype=int32)

In [59]:
# Multiplicacion
print(a * 10)
# Sumar
print(a + 7)
# Restar
print(a - 2)
# Dividir
print(a / 2)
# Mod
print(a % 3)

[100 100 100]
[17 17 17]
[8 8 8]
[5. 5. 5.]
[1 1 1]


In [60]:
arreglo_muestra = np.arange(20).reshape(5,2,2)

In [61]:
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [65]:
respuesta = arreglo_muestra > 5
respuesta

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [66]:
arreglo_muestra[respuesta]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [70]:
respuesta = (arreglo_muestra > 5) & (arreglo_muestra < 12)
respuesta

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [71]:
arreglo_muestra[respuesta]

array([ 6,  7,  8,  9, 10, 11])

In [79]:
respuesta = (arreglo_muestra > 6) & (arreglo_muestra < 14) & (arreglo_muestra % 2==0)
arreglo_muestra[respuesta]

array([ 8, 10, 12])

In [80]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [81]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [82]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [83]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [84]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
arreglo_doce.sum()

66

In [86]:
arreglo_doce.min()

0

In [87]:
arreglo_doce.max()

11

In [88]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [89]:
arreglo_doce.reshape(3,2,2).sum(axis=0) #

array([[12, 15],
       [18, 21]])

In [90]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [91]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])