In [1]:
import numpy as np

In [2]:
arreglo_cero_diez = np.arange(11) ** 2
arreglo_cero_diez

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [3]:
type(arreglo_cero_diez)

numpy.ndarray

In [4]:
arreglo_cero_diez[0:7] #Funciona similar a los arreglos

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [5]:
arreglo_cero_diez[-1]

100

In [6]:
arreglo_cero_diez[-6:-1]

array([25, 36, 49, 64, 81], dtype=int32)

In [7]:
arreglo_cero_diez[2:-3]

array([ 4,  9, 16, 25, 36, 49], dtype=int32)

In [8]:
arreglo_cero_diez[:-3]

array([ 0,  1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [9]:
arreglo_cero_diez[:] #obtener todo el arreglo

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [10]:
arreglo_cero_diez [::2] #Numeros pares listados desde el principio hacia el final

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [11]:
arreglo_cero_diez [::-1] #Numeros listados desde el final hacia el principio

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [12]:
arreglo_cero_diez [::-2] #Numeros pares listados desde el final hacia el principio

array([100,  64,  36,  16,   4,   0], dtype=int32)